### ISSUE TITLE
Scraper during holidays

### ISSUE THREAD

**Issue by redfast00** [ZeusWPI/hydra#268] opened 2018-06-26 08:20 UTC
Right now, the scraper fails to scrape new menus because most restos are closed. This results in a mail getting sent every day. Should the scraper be stopped during holidays? Do we disable this in the cronjob or do we add some code that checks if restos are open?

**Comment by wschella** [comment] 2018-06-29 16:01
I prefer the last option.

**Comment by Silox** [comment] 2018-06-29 16:02
Last option will also work during other holidays/single days off

Op vr 29 jun. 2018 om 18:01 schreef Wout Schellaert <
notifications@github.com>:

**Comment by redfast00** [comment] 2018-06-30 09:12
Looked into it, the script [asserts](https://github.com/ZeusWPI/hydra/blob/master/scraper/resto.py#L200) that the menus for both this week and next week should always be available. [This](https://www.ugent.be/student/nl/meer-dan-studeren/resto/weekmenu-sintjansvest/overzicht/@@rss2json) is an example where that fails: there are no menus for next week. I don't know if there is an API endpoint where you can see what resto's are open. The other problem is that for users, there is a difference between a closed resto and a resto without a menu for that week.

**Comment by wschella** [comment] 2018-07-01 11:05
@redfast00 I propose we handle the UX by considering all as 'no menu available', users can guess what the cause is then. If the overview page (the one you linked) is empty, we should not error right? This is quite common.

**Comment by wschella** [comment] 2018-07-01 11:40
Let's git blame.

**Comment by wschella** [comment] 2018-07-01 11:42
It was @NoctuaNivalis 4 years ago, I feel it's safe to remove. We _should_ get errors if the overview page dictates theirs a menu, but we can't find it.

**Comment by NoctuaNivalis** [comment] 2018-07-02 08:18
:man_dancing:

**Comment by redfast00** [comment] 2018-07-04 07:58
See #272 for a possible fix

**Comment by wschella** [comment] 2018-07-04 10:22
We'll merge, and close this issue after observing results for a couple of days.

**Comment by redfast00** [comment] 2018-07-04 10:34
Okay, I'll deploy it when I have access to my computer then.

**Comment by niknetniko** [comment] 2020-09-06 15:16
This seems to have worked.

**Closed by niknetniko** 2020-09-06 15:16 UTC
